/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./src/components/AppLoading.vue')['default']
    ArrowNext: typeof import('./src/components/icons/ArrowNext.vue')['default']
    BotAnswer: typeof import('./src/components/bot-answer/BotAnswer.vue')['default']
    ChatBox: typeof import('./src/components/chat-box/ChatBox.vue')['default']
    ChatBubble: typeof import('./src/components/ChatBubble.vue')['default']
    ChatMessage: typeof import('./src/components/chat-message/ChatMessage.vue')['default']
    CurrenciesList: typeof import('./src/components/CurrenciesList.vue')['default']
    CurrencyInput: typeof import('./src/components/CurrencyInput.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NextArrow: typeof import('./src/components/icons/NextArrow.vue')['default']
    PrevArrow: typeof import('./src/components/icons/PrevArrow.vue')['default']
    RateCard: typeof import('./src/components/rates/RateCard.vue')['default']
    RateList: typeof import('./src/components/rates/RateList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderArrow: typeof import('./src/components/icons/SliderArrow.vue')['default']
    UserForm: typeof import('./src/components/user-form/UserForm.vue')['default']
    WidgetBox: typeof import('./src/components/WidgetBox.vue')['default']
    WidgetButton: typeof import('./src/components/WidgetButton.vue')['default']
    WidgetHeader: typeof import('./src/components/WidgetHeader.vue')['default']
  }
}
